#!/bin/sh
# $Id$

# Usage: athstatic progname options ...

# Replaces -lfoo options with /usr/athena/lib/libfoo.a if it exists,
# thus preferring static libraries to shared libraries for stuff in
# /usr/athena/lib.

progname=$1
shift

options=
for arg do
  case $arg in
  -l*)
    # Chop off the first two characters to get the library name.
    lib=`expr "$arg" : '..\(.*\)$'`
    if [ -f /usr/athena/lib/lib${lib}.a -a "$lib" != "perl" ]; then
      options="$options /usr/athena/lib/lib${lib}.a"
    else
      options="$options $arg"
    fi
    ;;
  *)
    options="$options $arg"
    ;;
  esac
done

echo "$progname" $options
exec "$progname" $options
