#!/bin/sh
# This is a wrapper script to point BARNOWL_DATA_DIR at the source dir
# if we're running from a build tree. barnowl.bin is the actual built
# binary.

SRCDIR=`dirname "${0}"`
EXE="$0.bin"

if test ! -x "$EXE"; then
    echo "Cannot find barnowl.bin" >&2
    exit 1
fi

BARNOWL_DATA_DIR="$SRCDIR/perl/"
BARNOWL_BIN_DIR="$SRCDIR/"
export BARNOWL_DATA_DIR
export BARNOWL_BIN_DIR
exec "$EXE" "$@"
