.TH owl 1 "10 Apr 2004"
.SH NAME
owl \- tty based zephyr client
.SH SYNOPSIS
.B owl
[ \-n
]
[ \-d
]
[ \-D
]
[ \-v
]
[ \-h
]
[ \-c
.I configfile
]
[ \-t
.I tty
]

.br
.SH DESCRIPTION
.B Owl
is a fully integrated tty based instant messaging client.  Currently
it supports AOL Instant Messenger and MIT Zephyr.  It is curses-based,
allows for emacs style editing of outgoing messages and uses a perl
configuration language for setting options and customizing message
formatting.  Owl will also run happily without a configuration file.

Once Owl is started, typing 'h' will display a help screen.  Typing
\':\' enters command mode, allowing the user to type an owl command
line.

.PP
.SH USE
The following command line options are avilable when running owl:

.B \-n
.IP
Do not subscribe to zephyr messages on startup.  By default Owl
subscribes to the default subscriptions and to anything found in
~/.zephyr.subs.  When this option is used no subscriptions are loaded.
.LP

.B \-c \fIconfigfile\fP
.IP
Specifiy an alternate config file for Owl to use.  The default
configuration file is ~/.owlconf
.LP

.B \-t \fItty\fP
.IP
Specifiy the tty name to use for the zephyr location.
.LP

.B \-v
.IP
Print the version number of owl and exit.
.LP

.B \-d
.IP
Enable debugging.  By default debugging information is placed in
/var/tmp/owldebug.
.LP

.B \-D
.IP
Enable debugging, but first delete any existing debugging file.
.LP

.B \-h
.IP
Print command line option help.
.LP

.SH AUTHOR
Written by James Kretchmar at the Massachusetts Institute of
Technology.
Comments, questions, and bug reports may be mailed to
\fBbug-owl@ktools.org\fP.
