.TH owl 1 "21 May 2002"
.SH NAME
owl \- tty based zephyr client
.SH SYNOPSIS
.B owl
[ \-n
]
[ \-c
.I configfile
]
[ \-t
.I tty
]
[ \-v
]

.br
.SH DESCRIPTION
.B Owl
is a fully integrated tty based zephyr client for sending and
receiving zephyrs.  It is curses-based, allows for emacs style editing
of outgoing messages and uses a perl configuration language for
setting options and customizing message formatting.  Owl will also run
happily without a configuration file.

Once owl is started typing 'h' will display a help screen.  Typing ':'
enters command mode, allowing the user to type an owl command line.

.PP
.SH USE
The following command line options are avilable when running owl:

.B \-n
.IP
Do not subscribe to messages on startup.  By default owl subscribes to
the default subscriptions and to anything found in ~/.zephyr.subs
.LP

.B \-c \fIconfigfile\fP
.IP
Specifiy an alternate config file for owl to use.  By default it looks
for ~/.owlconf
.LP

.B \-t \fItty\fP
.IP
Specifiy the tty name to use for the zephyr location.
.LP

.B \-v
.IP
Print the version number of owl and exit.
.LP

.SH AUTHOR
Written by James Kretchmar at the Massachusetts Institute of
Technology.
Comments, questions, and bug reports may be mailed to
\fBbug-ktools@mit.edu\fP.
